{{ if and .Values.auth.admin.enabled (not .Values.auth.admin.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.adminTokenSecretName" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "vaultwarden.adminTokenSecretName" .)) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $adminToken := (get $secretData "token") | default (randAlphaNum 32 | b64enc) }}
  token: {{ $adminToken | quote }} 
{{ end }}
