apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vaultwarden.fullname" . }}-data
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
  {{- with .Values.pvc.annotations }}
  annotations:
  {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  accessModes:
    {{- .Values.pvc.accessModes | toYaml | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
