{{ if .Values.mariadb.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.fullname" . }}-db-secret
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ include "vaultwarden.dbPassword" . | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.fullname" . }}-db-url
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
type: Opaque
stringData:
  db_url: "mysql://{{ .Values.global.database.username }}:{{ include "vaultwarden.dbPassword" . | urlquery }}@{{ include "vaultwarden.mariadbServiceName" .}}/{{ .Values.global.database.database }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.fullname" . }}-mariadb-client
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
stringData:
  my.cnf: |-
    [client]
    host='{{ include "vaultwarden.mariadbServiceName" . }}'
    database='{{ .Values.global.database.database }}'
    user='{{ .Values.global.database.username }}'
    password='{{ include "vaultwarden.dbPassword" . }}'
{{ end }}
