{{ if .Values.pvc.sqlite.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vaultwarden.fullname" . }}-sqlite
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
  {{- with .Values.pvc.sqlite.annotations }}
  annotations:
  {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  storageClassName: {{ .Values.pvc.sqlite.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.sqlite.size }}
{{ end }}
