
{{ if and .Values.smtp.enabled (not .Values.smtp.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.smtpSecretName" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.smtp.username | b64enc }}
  password: {{ .Values.smtp.password | b64enc }}
{{ end }}
